name: ABI Go Bindings Checker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

env:
  GO_VERSION: "1.20.8"

jobs:
  abi_binding:
    name: abi_binding
    runs-on: ubuntu-20.04

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout Teleporter repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install forge and generate ABI Go bindings
        run: |
          BASE_DIR=${XDG_CONFIG_HOME:-$HOME}
          curl -L https://foundry.paradigm.xyz | bash
          source $HOME/.bashrc
          $BASE_DIR/.foundry/bin/foundryup
          export GOPATH=$HOME/go
          export PATH="$PATH:$BASE_DIR/.foundry/bin"
          export PATH="$PATH:$GOPATH/bin"
          ./scripts/abi_bindings.sh

      - name: Check for clean branch
        if: ${{ !contains(github.ref, 'dependabot/') }}
        run: git --no-pager diff && git --no-pager diff --quiet

      - name: Dependabot commit changes
        if: contains(github.ref, 'dependabot/')
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Dependabot Github Action commit

      - name: Run ABI Binding Unit Tests
        run: |
          cd abi-bindings/go
          go test ./...
