# Copyright (C) 2023, Ava Labs, Inc. All rights reserved.
# See the file LICENSE for licensing terms.

name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

env:
  GO_VERSION: 1.20.10

jobs:
  e2e_tests:
    name: e2e_tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repositories and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run E2E Tests
        # Forge installs to BASE_DIR, but updates the PATH definition in $HOME/.bashrc
        run: |
          export PATH="$PATH:$GOPATH/bin"
          ./scripts/local/e2e_test.sh
